spring:
  application:
    name: ForumDQC

  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
    database: postgresql

  session:
    jdbc:
      initialize-schema: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server.tomcat.max-http-response-header-size: 1048576

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: INFO